[package]
name = "ffi_rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
csbindgen = "1.8.0"

[dependencies]
http = "1.3.1"
once_cell = "1.21.3"
reqwest = "0.12.23"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "sync", "time"] }
